### ISSUE TITLE
Issue with paths not working in variables - v3.5

### ISSUE THREAD

**Issue by c41** [bdkjones/CodeKit#434]
In CodeKit versions up to 3.4.2, using a file path as a variable within a kit template worked.
eg: if this is my kit template:

```
<!-- $cssPath = ../../ -->
<!-- @import "header" -->
<body>
</body>
</html>
```
and this is my _header.kit include:

```
<!DOCTYPE html>
<html lang="en">
<head>
	<link href="<!--$cssPath-->css/styles.css" rel="stylesheet">
</head>
```
my exported html would look like this:

```
<!DOCTYPE html>
<html lang="en">
<head>
	<link href="../../css/styles.css" rel="stylesheet">
</head>
<body>
</body>
</html>
```
but - starting in CodeKit v3.5, that no longer works. 
My exported html now looks like this below, note the css path is broken/incomplete on that line, and then the &lt;/head&gt; tag is missing. so when rendered I see nothing.
```
<!DOCTYPE html>
<html lang="en">
<head>
	<link href="../../
<body>
</body>
</html>
```
Am I doing something wrong?
This happens silently - ie: CodeKit doesn't throw the normal 'compilation failed' error in the log.
Pete

**Comment by bdkjones** [comment]
Thanks for the heads up. Can you post a small demo project showing the issue? I’ll take a look at this tomorrow night.

**Comment by c41** [comment]
Sure - the bare minimum that's required to demo the issue is just a few files containing the above.
Here's a link to a zipped folder that includes the config.conkit3 file:
https://www.dropbox.com/s/hsoyc19ck0u9myf/codekit-test.zip?dl=0

Note the template.html in this project has been exported with CK 3.5 and shows the malformed output. If you re-generate the html without any changes to the .kit files, using CK 3.4.2, you'll see the different output.

**Comment by devilskitchen** [comment]
I have been getting the same—and now none of my Kit files with variables will compile.

There seems to be an issue around spaces: Codekit now seems to insist on them when you call the variable, e.g. `<!--$myVar-->` breaks, and you must use `<!-- $myVar -->`

A bit of a pain, really.

**Comment by bdkjones** [comment]
Yep. I’m looking into it now.

**Comment by bdkjones** [comment]
Found the issue. It's related to a change made to handle cases where a special comment immediately followed an `@` character, such as:

    mailto:"me@.com"

I've fixed it and will push a 3.5.1 update live tonight to get it out. Sorry for the incompetence.

**Comment by devilskitchen** [comment]
Oh, good lord, Bryan—don't apologise. These things happen. And, let's face it, you didn't _have_ to create `.kit` (but I use it. A LOT)...

The only reason that it was inconvenient was that I had made a colossal boo-boo on a Kit site, and needed to get it sorted asap. Typical!

**Comment by devilskitchen** [comment]
Having said that, I'm not sure that your suggested fix will do the job. Hang on—will upload a project...

**Comment by devilskitchen** [comment]
This project compiles fine in 3.4.2, but fails in 3.5. The variable failing is  because it is the first variable called in the relevant files.

[tech-v5-release-notes.zip](https://github.com/bdkjones/CodeKit/files/1709340/tech-v5-release-notes.zip)

**Comment by c41** [comment]
Thanks Bryan! I echo devilskitchen - no need to apologise. Quite the contrary - thanks for fixing the prob so quickly. Thanks for your work and the app! Pete

**Comment by bdkjones** [comment]
Fixed in 3.5.1.

**Comment by devilskitchen** [comment]
Confirmed fixed. Thanks @bdkjones—you are a god.

P.S. One of our devs is obsessed with the phrase "stuff and things", and has been trying to persuade us to call one of our releases by that codename (unsuccessfully so far). He was gutted when I showed him your release notes... :-D
